# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YPuSb_vntNyOeN_uNSSwFTWSffMxaSl
"""

pip install -U transformers

!pip install -U transformers

from transformers import pipeline

classifier = pipeline("sentiment-analysis")

result = classifier("I love using Hugging Face Transformers!")
print(result)

from transformers import pipeline

# Initialize the pipeline with the Granite model
# Note: This will download several gigabytes of data on the first run
pipe = pipeline("text-generation", model="ibm-granite/granite-3.1-2b-instruct", device_map="auto")

messages = [
    {"role": "user", "content": "Who are you?"},
]

# Run the pipeline
output = pipe(messages, max_new_tokens=100)

# Print the result
print(output[0]['generated_text'][-1]['content'])

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

# Define the model ID
model_id = "ibm-granite/granite-3.1-2b-instruct" # Updated to 3.1, or use 3.0 from your image

# 1. Load the tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.bfloat16
)

# 2. Prepare the chat message
messages = [
    {"role": "user", "content": "Who are you?"},
]

# 3. Apply chat template and tokenize
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

# 4. Generate the response
outputs = model.generate(**inputs, max_new_tokens=40)

# 5. Decode and print (stripping the input prompt)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True))

pip install -q gradio

!pip install -q gradio

!pip install -q gradio

import gradio as gr
print(gr.__version__)

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple,Dict,List
import random

import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random

# ==============================================================================
# HTML QUICK-STYLER - ADVANCED VERSION (FIXED)
# ==============================================================================

class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""

    @staticmethod
    def generate_palette(style: str = "modern") -> Dict[str, str]:
        """Generate a cohesive color palette based on style"""
        palettes = {
            "modern": {
                "primary": "#2C3E50", "secondary": "#34495E", "accent": "#E74C3C",
                "background": "#ECF0F1", "text": "#2C3E50", "light_text": "#ECF0F1"
            },
            "vibrant": {
                "primary": "#FF5733", "secondary": "#FFC300", "accent": "#C70039",
                "background": "#DAF7A6", "text": "#581845", "light_text": "#FFFFFF"
            },
            "calm": {
                "primary": "#81B29A", "secondary": "#F2CC8F", "accent": "#E07A5F",
                "background": "#F4F1DE", "text": "#3D405B", "light_text": "#F4F1DE"
            },
            "sunset": {
                "primary": "#FF7E5F", "secondary": "#FEB47B", "accent": "#F6416C",
                "background": "#FFF5EB", "text": "#2C1A27", "light_text": "#FFF5EB"
            }
        }
        return palettes.get(style, palettes["modern"])

import gradio as gr

def generate_html(title, description, style):
    # Use the ColorPaletteGenerator to get colors
    palette = ColorPaletteGenerator.generate_palette(style)

    html_output = f"""
    <html>
      <head>
        <style>
          body {{
            font-family: sans-serif;
            background-color: {palette['background']};
            color: {palette['text']};
          }}
          h1 {{
            color: {palette['primary']};
          }}
          .style-info {{
            color: {palette['accent']};
          }}
        </style>
      </head>
      <body>
        <h1>{title}</h1>
        <p>{description}</p>
        <div class='style-info'>Style selected: {style}</div>
      </body>
    </html>
    """
    return html_output

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🎨 HTML Quick-Styler Advanced")

    with gr.Row():
        # Left Column: Inputs
        with gr.Column():
            gr.Markdown("### 📄 Page Details")
            title = gr.Textbox(label="Page Title", placeholder="Modern Portfolio Website")
            desc = gr.TextArea(label="Page Description & Sections", lines=5)
            # Update choices to include 'sunset'
            style = gr.Dropdown(label="Color Style", choices=["modern", "vibrant", "calm", "sunset", "minimalist"]) # Added sunset
            generate_btn = gr.Button("Generate HTML", variant="primary")

        # Right Column: Output
        with gr.Column():
            gr.Markdown("### 🖥️ Output")
            output_code = gr.Code(label="Generated HTML/CSS", language="html")

    # Connect the button to the function
    generate_btn.click(fn=generate_html, inputs=[title, desc, style], outputs=output_code)

# share=True creates a public URL so you can view the UI properly
demo.launch(share=True)